In [1]:
# Dependencies
import pandas as pd
import json
import requests
import time
import pymysql
pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine
from pprint import pprint

In [55]:
# Import Firt Data Source: Dog Names CSV, and format
dog_names_file = "resources/dog_names.csv"
dog_names_df = pd.read_csv(dog_names_file)

dog_names_df_clean = dog_names_df.rename(columns={"Row_Labels": "Name",
                                                  "Count_AnimalName": "Count"})

dog_names_df_clean['Name'] = dog_names_df_clean.Name.str.title()
dog_names_df_clean.set_index("Name", inplace=True)

dog_names_df_clean.head(10)

         Count
Name
1            1
2            2
40804        1
90201        1
90203        1
102201       1
3010271      1
March        2
April       51
August      14

In [56]:
# Import second source of Data: State Names CSV
state_names_file = "resources/state_names.csv"
state_names_df = pd.read_csv(state_names_file)

state_names_df.set_index("Id", inplace=True)
state_names_df.set_index("Name", inplace=True)

state_names_df.head()

            Year Gender State  Count
Name
Mary      1910.0      F    AK   14.0
Annie     1910.0      F    AK   12.0
Anna      1910.0      F    AK   10.0
Margaret  1910.0      F    AK    8.0
Helen     1910.0      F    AK    7.0

In [57]:
# Filter data by year: 2011 or greater
state_names_2000_df = state_names_df.loc[state_names_df['Year'] >= 2011]
state_names_2000_df.head()

            Year Gender State  Count
Name
Olivia    2011.0      F    AK   60.0
Emma      2011.0      F    AK   56.0
Isabella  2011.0      F    AK   50.0
Madison   2011.0      F    AK   46.0
Sophia    2011.0      F    AK   44.0

In [58]:
# Filter Data by State: NY
state_names_2000_NY_df = state_names_2000_df.loc[state_names_2000_df["State"] == "NY"]
state_names_2000_NY_df.head()

            Year Gender State   Count
Name
Sophia    2011.0      F    NY  1453.0
Isabella  2011.0      F    NY  1415.0
Olivia    2011.0      F    NY  1175.0
Emma      2011.0      F    NY  1122.0
Ava       2011.0      F    NY   954.0

In [59]:
# Filter data by top 100 Names from NY
state_names_2000_NY_100_df = state_names_2000_NY_df.iloc[:100]
state_names_2000_NY_100_df.head()

            Year Gender State   Count
Name
Sophia    2011.0      F    NY  1453.0
Isabella  2011.0      F    NY  1415.0
Olivia    2011.0      F    NY  1175.0
Emma      2011.0      F    NY  1122.0
Ava       2011.0      F    NY   954.0

In [42]:
# Third source of data: Name Origins API 

# Connection:

# API URLs & Key
origin_url = f"https://www.behindthename.com/api/lookup.json"
related_url = f"https://www.behindthename.com/api/related.json"
api_key = "&key=an594138819"

# Test Example:
query_name = "Emily"
query_name_origin = origin_url + "?name=" + query_name + api_key
query_name_related = related_url + "?name=" + query_name + api_key

In [43]:
# Test response for origin_url
origin_data = requests.get(query_name_origin).json()
pprint(origin_data)

[{'gender': 'f',
  'name': 'Emily',
  'usages': [{'usage_code': 'eng',
              'usage_full': 'English',
              'usage_gender': 'f'}]}]

In [44]:
# Test response for related_url
related_data = requests.get(query_name_related).json()
pprint(related_data)

{'names': ['Amilia',
           'Em',
           'Emalee',
           'Emely',
           'Emilee',
           'Emilia',
           'Emmie',
           'Emmy',
           'Millie',
           'Milly']}

In [38]:
# Create a Name list from top 100 names:
name_list = []

for name in state_names_2000_NY_100_df["Name"]:
    name_list.append(name)
print(name_list)

['Sophia', 'Isabella', 'Olivia', 'Emma', 'Ava', 'Emily', 'Mia', 'Madison', 'Abigail', 'Chloe', 'Leah', 'Ella', 'Sofia', 'Gabriella', 'Grace', 'Sarah', 'Samantha', 'Gianna', 'Victoria', 'Elizabeth', 'Hailey', 'Ashley', 'Lily', 'Charlotte', 'Brianna', 'Julia', 'Natalie', 'Zoe', 'Kayla', 'Amelia', 'Hannah', 'Arianna', 'Rachel', 'Angelina', 'Esther', 'Maya', 'Alexandra', 'Alyssa', 'Kaylee', 'Alexa', 'Anna', 'Allison', 'Addison', 'Avery', 'Aaliyah', 'Savannah', 'Alexis', 'Lillian', 'Evelyn', 'Layla', 'Camila', 'Katherine', 'Taylor', 'Sara', 'Riley', 'Nevaeh', 'Nicole', 'Makayla', 'Eva', 'Zoey', 'Peyton', 'Brooke', 'Ariana', 'Khloe', 'Sophie', 'Aubrey', 'Bella', 'Kylie', 'Chaya', 'Claire', 'Lauren', 'Adriana', 'Madeline', 'Melanie', 'Jasmine', 'Molly', 'Valentina', 'Kimberly', 'Kaitlyn', 'Maria', 'Michelle', 'Juliana', 'Mackenzie', 'Madelyn', 'Miriam', 'Scarlett', 'Genesis', 'Julianna', 'Stella', 'London', 'Natalia', 'Sydney', 'Serenity', 'Faith', 'Gabrielle', 'Jessica', 'Morgan', 'Naomi', 'Paige', 'Rebecca']

In [45]:
# For loop call to API to retrieve origins from 'name_list':
genders = []
origins = []
origins_two = []
related_names = []

name_data=[]
for name in name_list:
    origin_query = origin_url + "?name=" + name + api_key
    related_query = related_url + "?name=" + name + api_key
    print(origin_query)
    print(related_query)
    print("----------------------------")
    response = requests.get(origin_query).json()
    response2 = requests.get(related_query).json()
    print(response[0]['gender'])
    print(response[0]['usages'][0]['usage_full'])
#     print(response[0]['usages'][1]['usage_full'])
    print(response2['names'][0:2])
    genders.append(response[0]['gender'])
    origins.append(response[0]['usages'][0]['usage_full'])
#     origins_two.append(response[0]['usages'][1]['usage_full'])
    related_names.append(response2['names'][0:2])

https://www.behindthename.com/api/lookup.json?name=Sophia&key=an594138819
https://www.behindthename.com/api/related.json?name=Sophia&key=an594138819
----------------------------
f
English
['Sofia', 'Sophy']
https://www.behindthename.com/api/lookup.json?name=Isabella&key=an594138819
https://www.behindthename.com/api/related.json?name=Isabella&key=an594138819
----------------------------
f
Italian
['Bella', 'Belle']
https://www.behindthename.com/api/lookup.json?name=Olivia&key=an594138819
https://www.behindthename.com/api/related.json?name=Olivia&key=an594138819
----------------------------
f
English
['Alivia', 'Liv']
https://www.behindthename.com/api/lookup.json?name=Emma&key=an594138819
https://www.behindthename.com/api/related.json?name=Emma&key=an594138819
----------------------------
f
English
['Em', 'Ema']
https://www.behindthename.com/api/lookup.json?name=Ava&key=an594138819
https://www.behindthename.com/api/related.json?name=Ava&key=an594138819
----------------------------
f
English
['Eva', 'Avelina']
https://www.behindthename.com/api/lookup.json?name=Emily&key=an594138819
https://www.behindthename.com/api/related.json?name=Emily&key=an594138819
----------------------------
f
English
['Amilia', 'Em']
https://www.behindthename.com/api/lookup.json?name=Mia&key=an594138819
https://www.behindthename.com/api/related.json?name=Mia&key=an594138819
----------------------------
f
Swedish
['Jet', 'Jette']
https://www.behindthename.com/api/lookup.json?name=Madison&key=an594138819
https://www.behindthename.com/api/related.json?name=Madison&key=an594138819
----------------------------
fm
English
['Maddie', 'Maddison']
https://www.behindthename.com/api/lookup.json?name=Abigail&key=an594138819
https://www.behindthename.com/api/related.json?name=Abigail&key=an594138819
----------------------------
f
English
['Abbey', 'Abbi']
https://www.behindthename.com/api/lookup.json?name=Chloe&key=an594138819
https://www.behindthename.com/api/related.json?name=Chloe&key=an594138819
----------------------------
f
English
['Khloe']
https://www.behindthename.com/api/lookup.json?name=Leah&key=an594138819
https://www.behindthename.com/api/related.json?name=Leah&key=an594138819
----------------------------
f
English
[]
https://www.behindthename.com/api/lookup.json?name=Ella&key=an594138819
https://www.behindthename.com/api/related.json?name=Ella&key=an594138819
----------------------------
f
English
['Bess', 'Bessie']
https://www.behindthename.com/api/lookup.json?name=Sofia&key=an594138819
https://www.behindthename.com/api/related.json?name=Sofia&key=an594138819
----------------------------
f
Norwegian
['Sofiya', 'Sofya']
https://www.behindthename.com/api/lookup.json?name=Gabriella&key=an594138819
https://www.behindthename.com/api/related.json?name=Gabriella&key=an594138819
----------------------------
f
Italian
['Briella', 'Gabi']
https://www.behindthename.com/api/lookup.json?name=Grace&key=an594138819
https://www.behindthename.com/api/related.json?name=Grace&key=an594138819
----------------------------
f
English
['Gracelyn', 'Gracie']
https://www.behindthename.com/api/lookup.json?name=Sarah&key=an594138819
https://www.behindthename.com/api/related.json?name=Sarah&key=an594138819
----------------------------
f
English
['Sadie', 'Sal']
https://www.behindthename.com/api/lookup.json?name=Samantha&key=an594138819
https://www.behindthename.com/api/related.json?name=Samantha&key=an594138819
----------------------------
f
English
['Sam', 'Samanta']
https://www.behindthename.com/api/lookup.json?name=Gianna&key=an594138819
https://www.behindthename.com/api/related.json?name=Gianna&key=an594138819
----------------------------
f
Italian
['Gia', 'Giannina']
https://www.behindthename.com/api/lookup.json?name=Victoria&key=an594138819
https://www.behindthename.com/api/related.json?name=Victoria&key=an594138819
----------------------------
f
English
['Tori', 'Toria']
https://www.behindthename.com/api/lookup.json?name=Elizabeth&key=an594138819
https://www.behindthename.com/api/related.json?name=Elizabeth&key=an594138819
----------------------------
f
English
['Bess', 'Bessie']
https://www.behindthename.com/api/lookup.json?name=Hailey&key=an594138819
https://www.behindthename.com/api/related.json?name=Hailey&key=an594138819
----------------------------
f
English (Modern)
['Hailee', 'Hailie']
https://www.behindthename.com/api/lookup.json?name=Ashley&key=an594138819
https://www.behindthename.com/api/related.json?name=Ashley&key=an594138819
----------------------------
fm
English
['Ashlea', 'Ashlee']
https://www.behindthename.com/api/lookup.json?name=Lily&key=an594138819
https://www.behindthename.com/api/related.json?name=Lily&key=an594138819
----------------------------
f
English
['Leanna', 'Liana']
https://www.behindthename.com/api/lookup.json?name=Charlotte&key=an594138819
https://www.behindthename.com/api/related.json?name=Charlotte&key=an594138819
----------------------------
f
French
['Carla', 'Carlene']
https://www.behindthename.com/api/lookup.json?name=Brianna&key=an594138819
https://www.behindthename.com/api/related.json?name=Brianna&key=an594138819
----------------------------
f
English
['Breana', 'Breann']
https://www.behindthename.com/api/lookup.json?name=Julia&key=an594138819
https://www.behindthename.com/api/related.json?name=Julia&key=an594138819
----------------------------
f
English
['Iulia', 'Jools']
https://www.behindthename.com/api/lookup.json?name=Natalie&key=an594138819
https://www.behindthename.com/api/related.json?name=Natalie&key=an594138819
----------------------------
f
English
['Nat', 'Natalee']
https://www.behindthename.com/api/lookup.json?name=Zoe&key=an594138819
https://www.behindthename.com/api/related.json?name=Zoe&key=an594138819
----------------------------
f
English
['Zoë', 'Zoey']
https://www.behindthename.com/api/lookup.json?name=Kayla&key=an594138819
https://www.behindthename.com/api/related.json?name=Kayla&key=an594138819
----------------------------
f
English
['Caetlin', 'Caitlin']
https://www.behindthename.com/api/lookup.json?name=Amelia&key=an594138819
https://www.behindthename.com/api/related.json?name=Amelia&key=an594138819
----------------------------
f
English
['Amalia', 'Emelia']
https://www.behindthename.com/api/lookup.json?name=Hannah&key=an594138819
https://www.behindthename.com/api/related.json?name=Hannah&key=an594138819
----------------------------
f
English
['Chanah', 'Channah']
https://www.behindthename.com/api/lookup.json?name=Arianna&key=an594138819
https://www.behindthename.com/api/related.json?name=Arianna&key=an594138819
----------------------------
f
Italian
[]
https://www.behindthename.com/api/lookup.json?name=Rachel&key=an594138819
https://www.behindthename.com/api/related.json?name=Rachel&key=an594138819
----------------------------
f
English
['Rachael', 'Racheal']
https://www.behindthename.com/api/lookup.json?name=Angelina&key=an594138819
https://www.behindthename.com/api/related.json?name=Angelina&key=an594138819
----------------------------
f
Italian
['Andżelika', 'Ángela']
https://www.behindthename.com/api/lookup.json?name=Esther&key=an594138819
https://www.behindthename.com/api/related.json?name=Esther&key=an594138819
----------------------------
f
English
['Essie', 'Esta']
https://www.behindthename.com/api/lookup.json?name=Maya&key=an594138819
https://www.behindthename.com/api/related.json?name=Maya&key=an594138819
----------------------------
f
Hinduism
[]
https://www.behindthename.com/api/lookup.json?name=Alexandra&key=an594138819
https://www.behindthename.com/api/related.json?name=Alexandra&key=an594138819
----------------------------
f
English
['Ale', 'Alejandra']
https://www.behindthename.com/api/lookup.json?name=Alyssa&key=an594138819
https://www.behindthename.com/api/related.json?name=Alyssa&key=an594138819
----------------------------
f
English
['Alease', 'Alecia']
https://www.behindthename.com/api/lookup.json?name=Kaylee&key=an594138819
https://www.behindthename.com/api/related.json?name=Kaylee&key=an594138819
----------------------------
f
English (Modern)
['Caelie', 'Caetlin']
https://www.behindthename.com/api/lookup.json?name=Alexa&key=an594138819
https://www.behindthename.com/api/related.json?name=Alexa&key=an594138819
----------------------------

f
English
['Alex', 'Alexandra']
https://www.behindthename.com/api/lookup.json?name=Anna&key=an594138819
https://www.behindthename.com/api/related.json?name=Anna&key=an594138819
----------------------------
f
English
['Aina', 'Ana']
https://www.behindthename.com/api/lookup.json?name=Allison&key=an594138819
https://www.behindthename.com/api/related.json?name=Allison&key=an594138819
----------------------------
f
English
['Adelaide', 'Alease']
https://www.behindthename.com/api/lookup.json?name=Addison&key=an594138819
https://www.behindthename.com/api/related.json?name=Addison&key=an594138819
----------------------------
fm
English
['Addyson']
https://www.behindthename.com/api/lookup.json?name=Avery&key=an594138819
https://www.behindthename.com/api/related.json?name=Avery&key=an594138819
----------------------------
mf
English
[]
https://www.behindthename.com/api/lookup.json?name=Aaliyah&key=an594138819
https://www.behindthename.com/api/related.json?name=Aaliyah&key=an594138819
----------------------------
f
Arabic
['Alea', 'Aleah']
https://www.behindthename.com/api/lookup.json?name=Savannah&key=an594138819
https://www.behindthename.com/api/related.json?name=Savannah&key=an594138819
----------------------------
f
English
['Savanna', 'Zavanna']
https://www.behindthename.com/api/lookup.json?name=Alexis&key=an594138819
https://www.behindthename.com/api/related.json?name=Alexis&key=an594138819
----------------------------
mf
German
['Alexia', 'Alexina']
https://www.behindthename.com/api/lookup.json?name=Lillian&key=an594138819
https://www.behindthename.com/api/related.json?name=Lillian&key=an594138819
----------------------------
f
English
['Bess', 'Bessie']
https://www.behindthename.com/api/lookup.json?name=Evelyn&key=an594138819
https://www.behindthename.com/api/related.json?name=Evelyn&key=an594138819
----------------------------
fm
English
['Evaline', 'Evalyn']
https://www.behindthename.com/api/lookup.json?name=Layla&key=an594138819
https://www.behindthename.com/api/related.json?name=Layla&key=an594138819
----------------------------
f
Arabic
['Laila', 'Leila']
https://www.behindthename.com/api/lookup.json?name=Camila&key=an594138819
https://www.behindthename.com/api/related.json?name=Camila&key=an594138819
----------------------------
f
Spanish
[]
https://www.behindthename.com/api/lookup.json?name=Katherine&key=an594138819
https://www.behindthename.com/api/related.json?name=Katherine&key=an594138819
----------------------------
f
English
['Caelie', 'Caileigh']
https://www.behindthename.com/api/lookup.json?name=Taylor&key=an594138819
https://www.behindthename.com/api/related.json?name=Taylor&key=an594138819
----------------------------
mf
English
[]
https://www.behindthename.com/api/lookup.json?name=Sara&key=an594138819
https://www.behindthename.com/api/related.json?name=Sara&key=an594138819
----------------------------
f
Greek
['Saara', 'Sadie']
https://www.behindthename.com/api/lookup.json?name=Riley&key=an594138819
https://www.behindthename.com/api/related.json?name=Riley&key=an594138819
----------------------------
mf
English
['Ryley']
https://www.behindthename.com/api/lookup.json?name=Nevaeh&key=an594138819
https://www.behindthename.com/api/related.json?name=Nevaeh&key=an594138819
----------------------------
f
English (Modern)
[]
https://www.behindthename.com/api/lookup.json?name=Nicole&key=an594138819
https://www.behindthename.com/api/related.json?name=Nicole&key=an594138819
----------------------------
f
French
['Colette', 'Coline']
https://www.behindthename.com/api/lookup.json?name=Makayla&key=an594138819
https://www.behindthename.com/api/related.json?name=Makayla&key=an594138819
----------------------------
f
English (Modern)
['Mckayla', 'Mica']
https://www.behindthename.com/api/lookup.json?name=Eva&key=an594138819
https://www.behindthename.com/api/related.json?name=Eva&key=an594138819
----------------------------
f
Spanish
['Ava', 'Eef']
https://www.behindthename.com/api/lookup.json?name=Zoey&key=an594138819
https://www.behindthename.com/api/related.json?name=Zoey&key=an594138819
----------------------------
f
English (Modern)
['Zoe', 'Zoie']
https://www.behindthename.com/api/lookup.json?name=Peyton&key=an594138819
https://www.behindthename.com/api/related.json?name=Peyton&key=an594138819
----------------------------
mf
English
[]
https://www.behindthename.com/api/lookup.json?name=Brooke&key=an594138819
https://www.behindthename.com/api/related.json?name=Brooke&key=an594138819
----------------------------
f
English
[]
https://www.behindthename.com/api/lookup.json?name=Ariana&key=an594138819
https://www.behindthename.com/api/related.json?name=Ariana&key=an594138819
----------------------------
f
Portuguese
['Aryana']
https://www.behindthename.com/api/lookup.json?name=Khloe&key=an594138819
https://www.behindthename.com/api/related.json?name=Khloe&key=an594138819
----------------------------
f
English (Modern)
['Chloe']
https://www.behindthename.com/api/lookup.json?name=Sophie&key=an594138819
https://www.behindthename.com/api/related.json?name=Sophie&key=an594138819
----------------------------
f
French
['Sofie', 'Sophy']
https://www.behindthename.com/api/lookup.json?name=Aubrey&key=an594138819
https://www.behindthename.com/api/related.json?name=Aubrey&key=an594138819
----------------------------
mf
English
['Auberon']
https://www.behindthename.com/api/lookup.json?name=Bella&key=an594138819
https://www.behindthename.com/api/related.json?name=Bella&key=an594138819
----------------------------
f
English
['Belle', 'Elisabeth']
https://www.behindthename.com/api/lookup.json?name=Kylie&key=an594138819
https://www.behindthename.com/api/related.json?name=Kylie&key=an594138819
----------------------------
f
English
['Kiley', 'Kilie']
https://www.behindthename.com/api/lookup.json?name=Chaya&key=an594138819
https://www.behindthename.com/api/related.json?name=Chaya&key=an594138819
----------------------------
f
Hebrew
[]
https://www.behindthename.com/api/lookup.json?name=Claire&key=an594138819
https://www.behindthename.com/api/related.json?name=Claire&key=an594138819
----------------------------
f
French
[]
https://www.behindthename.com/api/lookup.json?name=Lauren&key=an594138819
https://www.behindthename.com/api/related.json?name=Lauren&key=an594138819
----------------------------
fm
English
['Larrie', 'Larry']
https://www.behindthename.com/api/lookup.json?name=Adriana&key=an594138819
https://www.behindthename.com/api/related.json?name=Adriana&key=an594138819
----------------------------
f
Italian
['Adria', 'Adrianna']
https://www.behindthename.com/api/lookup.json?name=Madeline&key=an594138819
https://www.behindthename.com/api/related.json?name=Madeline&key=an594138819
----------------------------
f
English
['Madalyn', 'Maddie']
https://www.behindthename.com/api/lookup.json?name=Melanie&key=an594138819
https://www.behindthename.com/api/related.json?name=Melanie&key=an594138819
----------------------------
f
English
['Malinda', 'Mel']
https://www.behindthename.com/api/lookup.json?name=Jasmine&key=an594138819
https://www.behindthename.com/api/related.json?name=Jasmine&key=an594138819
----------------------------
f
English
['Jasmin', 'Jasmyn']
https://www.behindthename.com/api/lookup.json?name=Molly&key=an594138819
https://www.behindthename.com/api/related.json?name=Molly&key=an594138819
----------------------------
f
English
['Mae', 'Maleah']
https://www.behindthename.com/api/lookup.json?name=Valentina&key=an594138819
https://www.behindthename.com/api/related.json?name=Valentina&key=an594138819
----------------------------
f
Italian
['Tina']
https://www.behindthename.com/api/lookup.json?name=Kimberly&key=an594138819
https://www.behindthename.com/api/related.json?name=Kimberly&key=an594138819
----------------------------
f
English
['Kim', 'Kimberlee']
https://www.behindthename.com/api/lookup.json?name=Kaitlyn&key=an594138819
https://www.behindthename.com/api/related.json?name=Kaitlyn&key=an594138819
----------------------------
f
English (Modern)
['Caetlin', 'Caitlin']
https://www.behindthename.com/api/lookup.json?name=Maria&key=an594138819
https://www.behindthename.com/api/related.json?name=Maria&key=an594138819
----------------------------
fm
Italian
['Jet', 'Jette']
https://www.behindthename.com/api/lookup.json?name=Michelle&key=an594138819
https://www.behindthename.com/api/related.json?name=Michelle&key=an594138819
----------------------------

f
French
['Chelle', 'Micha']
https://www.behindthename.com/api/lookup.json?name=Juliana&key=an594138819
https://www.behindthename.com/api/related.json?name=Juliana&key=an594138819
----------------------------
f
Dutch
['Iuliana', 'Juliane']
https://www.behindthename.com/api/lookup.json?name=Mackenzie&key=an594138819
https://www.behindthename.com/api/related.json?name=Mackenzie&key=an594138819
----------------------------
fm
English
['Makenzie', 'Mckenzie']
https://www.behindthename.com/api/lookup.json?name=Madelyn&key=an594138819
https://www.behindthename.com/api/related.json?name=Madelyn&key=an594138819
----------------------------
f
English
['Madalyn', 'Maddie']
https://www.behindthename.com/api/lookup.json?name=Miriam&key=an594138819
https://www.behindthename.com/api/related.json?name=Miriam&key=an594138819
----------------------------
f
Hebrew
['Mirjam']
https://www.behindthename.com/api/lookup.json?name=Scarlett&key=an594138819
https://www.behindthename.com/api/related.json?name=Scarlett&key=an594138819
----------------------------
f
English
['Scarlet']
https://www.behindthename.com/api/lookup.json?name=Genesis&key=an594138819
https://www.behindthename.com/api/related.json?name=Genesis&key=an594138819
----------------------------
f
English (Modern)
[]
https://www.behindthename.com/api/lookup.json?name=Julianna&key=an594138819
https://www.behindthename.com/api/related.json?name=Julianna&key=an594138819
----------------------------
f
Hungarian
['Juliana', 'Julianne']
https://www.behindthename.com/api/lookup.json?name=Stella&key=an594138819
https://www.behindthename.com/api/related.json?name=Stella&key=an594138819
----------------------------
f
English
['Styliani']
https://www.behindthename.com/api/lookup.json?name=London&key=an594138819
https://www.behindthename.com/api/related.json?name=London&key=an594138819
----------------------------
fm
English (Modern)
['Londyn']
https://www.behindthename.com/api/lookup.json?name=Natalia&key=an594138819
https://www.behindthename.com/api/related.json?name=Natalia&key=an594138819
----------------------------
f
Polish
['Nat', 'Nata']
https://www.behindthename.com/api/lookup.json?name=Sydney&key=an594138819
https://www.behindthename.com/api/related.json?name=Sydney&key=an594138819
----------------------------
fm
English
['Cydney', 'Sydne']
https://www.behindthename.com/api/lookup.json?name=Serenity&key=an594138819
https://www.behindthename.com/api/related.json?name=Serenity&key=an594138819
----------------------------
f
English (Modern)
[]
https://www.behindthename.com/api/lookup.json?name=Faith&key=an594138819
https://www.behindthename.com/api/related.json?name=Faith&key=an594138819
----------------------------
f
English
['Fae', 'Faithe']
https://www.behindthename.com/api/lookup.json?name=Gabrielle&key=an594138819
https://www.behindthename.com/api/related.json?name=Gabrielle&key=an594138819
----------------------------
f
French
['Brielle', 'Gabby']
https://www.behindthename.com/api/lookup.json?name=Jessica&key=an594138819
https://www.behindthename.com/api/related.json?name=Jessica&key=an594138819
----------------------------
f
English
['Gessica', 'Jess']
https://www.behindthename.com/api/lookup.json?name=Morgan&key=an594138819
https://www.behindthename.com/api/related.json?name=Morgan&key=an594138819
----------------------------
mf
Welsh
['Morgaine', 'Morgen']
https://www.behindthename.com/api/lookup.json?name=Naomi&key=an594138819
https://www.behindthename.com/api/related.json?name=Naomi&key=an594138819
----------------------------
f
English
[]
https://www.behindthename.com/api/lookup.json?name=Paige&key=an594138819
https://www.behindthename.com/api/related.json?name=Paige&key=an594138819
----------------------------
f
English
[]
https://www.behindthename.com/api/lookup.json?name=Rebecca&key=an594138819
https://www.behindthename.com/api/related.json?name=Rebecca&key=an594138819
----------------------------
f
English
['Becca', 'Becci']

In [47]:
# Lists retrieved by for loop:
print(origins)
print(genders)
print(related_names)

['English', 'Italian', 'English', 'English', 'English', 'English', 'Swedish', 'English', 'English', 'English', 'English', 'English', 'Norwegian', 'Italian', 'English', 'English', 'English', 'Italian', 'English', 'English', 'English (Modern)', 'English', 'English', 'French', 'English', 'English', 'English', 'English', 'English', 'English', 'English', 'Italian', 'English', 'Italian', 'English', 'Hinduism', 'English', 'English', 'English (Modern)', 'English', 'English', 'English', 'English', 'English', 'Arabic', 'English', 'German', 'English', 'English', 'Arabic', 'Spanish', 'English', 'English', 'Greek', 'English', 'English (Modern)', 'French', 'English (Modern)', 'Spanish', 'English (Modern)', 'English', 'English', 'Portuguese', 'English (Modern)', 'French', 'English', 'English', 'English', 'Hebrew', 'French', 'English', 'Italian', 'English', 'English', 'English', 'English', 'Italian', 'English', 'English (Modern)', 'Italian', 'French', 'Dutch', 'English', 'English', 'Hebrew', 'English', 'English (Modern)', 'Hungarian', 'English', 'English (Modern)', 'Polish', 'English', 'English (Modern)', 'English', 'French', 'English', 'Welsh', 'English', 'English', 'English']
['f', 'f', 'f', 'f', 'f', 'f', 'f', 'fm', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'fm', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'fm', 'mf', 'f', 'f', 'mf', 'f', 'fm', 'f', 'f', 'f', 'mf', 'f', 'mf', 'f', 'f', 'f', 'f', 'f', 'mf', 'f', 'f', 'f', 'f', 'mf', 'f', 'f', 'f', 'f', 'fm', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'fm', 'f', 'f', 'fm', 'f', 'f', 'f', 'f', 'f', 'f', 'fm', 'f', 'fm', 'f', 'f', 'f', 'f', 'mf', 'f', 'f', 'f']
[['Sofia', 'Sophy'], ['Bella', 'Belle'], ['Alivia', 'Liv'], ['Em', 'Ema'], ['Eva', 'Avelina'], ['Amilia', 'Em'], ['Jet', 'Jette'], ['Maddie', 'Maddison'], ['Abbey', 'Abbi'], ['Khloe'], [], ['Bess', 'Bessie'], ['Sofiya', 'Sofya'], ['Briella', 'Gabi'], ['Gracelyn', 'Gracie'], ['Sadie', 'Sal'], ['Sam', 'Samanta'], ['Gia', 'Giannina'], ['Tori', 'Toria'], ['Bess', 'Bessie'], ['Hailee', 'Hailie'], ['Ashlea', 'Ashlee'], ['Leanna', 'Liana'], ['Carla', 'Carlene'], ['Breana', 'Breann'], ['Iulia', 'Jools'], ['Nat', 'Natalee'], ['Zoë', 'Zoey'], ['Caetlin', 'Caitlin'], ['Amalia', 'Emelia'], ['Chanah', 'Channah'], [], ['Rachael', 'Racheal'], ['Andżelika', 'Ángela'], ['Essie', 'Esta'], [], ['Ale', 'Alejandra'], ['Alease', 'Alecia'], ['Caelie', 'Caetlin'], ['Alex', 'Alexandra'], ['Aina', 'Ana'], ['Adelaide', 'Alease'], ['Addyson'], [], ['Alea', 'Aleah'], ['Savanna', 'Zavanna'], ['Alexia', 'Alexina'], ['Bess', 'Bessie'], ['Evaline', 'Evalyn'], ['Laila', 'Leila'], [], ['Caelie', 'Caileigh'], [], ['Saara', 'Sadie'], ['Ryley'], [], ['Colette', 'Coline'], ['Mckayla', 'Mica'], ['Ava', 'Eef'], ['Zoe', 'Zoie'], [], [], ['Aryana'], ['Chloe'], ['Sofie', 'Sophy'], ['Auberon'], ['Belle', 'Elisabeth'], ['Kiley', 'Kilie'], [], [], ['Larrie', 'Larry'], ['Adria', 'Adrianna'], ['Madalyn', 'Maddie'], ['Malinda', 'Mel'], ['Jasmin', 'Jasmyn'], ['Mae', 'Maleah'], ['Tina'], ['Kim', 'Kimberlee'], ['Caetlin', 'Caitlin'], ['Jet', 'Jette'], ['Chelle', 'Micha'], ['Iuliana', 'Juliane'], ['Makenzie', 'Mckenzie'], ['Madalyn', 'Maddie'], ['Mirjam'], ['Scarlet'], [], ['Juliana', 'Julianne'], ['Styliani'], ['Londyn'], ['Nat', 'Nata'], ['Cydney', 'Sydne'], [], ['Fae', 'Faithe'], ['Brielle', 'Gabby'], ['Gessica', 'Jess'], ['Morgaine', 'Morgen'], [], [], ['Becca', 'Becci']]

In [61]:
# Create Data frame for data retrieved from API:
name_origins_dict = {
    'Name': name_list,
    'Genders' : genders, 
    'Origins' : origins,
    'Related Names' : related_names
}

name_origins_df = pd.DataFrame.from_dict(name_origins_dict)
name_origins_df.set_index("Name", inplace=True)

name_origins_df

          Genders           Origins         Related Names
Name
Sophia          f           English        [Sofia, Sophy]
Isabella        f           Italian        [Bella, Belle]
Olivia          f           English         [Alivia, Liv]
Emma            f           English             [Em, Ema]
Ava             f           English        [Eva, Avelina]
Emily           f           English          [Amilia, Em]
Mia             f           Swedish          [Jet, Jette]
Madison        fm           English    [Maddie, Maddison]
Abigail         f           English         [Abbey, Abbi]
Chloe           f           English               [Khloe]
Leah            f           English                    []
Ella            f           English        [Bess, Bessie]
Sofia           f         Norwegian       [Sofiya, Sofya]
Gabriella       f           Italian       [Briella, Gabi]
Grace           f           English    [Gracelyn, Gracie]
Sarah           f           English          [Sadie, Sal]
Samantha        f           English        [Sam, Samanta]
Gianna          f           Italian       [Gia, Giannina]
Victoria        f           English         [Tori, Toria]
Elizabeth       f           English        [Bess, Bessie]
Hailey          f  English (Modern)      [Hailee, Hailie]
Ashley         fm           English      [Ashlea, Ashlee]
Lily            f           English       [Leanna, Liana]
Charlotte       f            French      [Carla, Carlene]
Brianna         f           English      [Breana, Breann]
Julia           f           English        [Iulia, Jools]
Natalie         f           English        [Nat, Natalee]
Zoe             f           English           [Zoë, Zoey]
Kayla           f           English    [Caetlin, Caitlin]
Amelia          f           English      [Amalia, Emelia]
...           ...               ...                   ...
Lauren         fm           English       [Larrie, Larry]
Adriana         f           Italian     [Adria, Adrianna]
Madeline        f           English     [Madalyn, Maddie]
Melanie         f           English        [Malinda, Mel]
Jasmine         f           English      [Jasmin, Jasmyn]
Molly           f           English         [Mae, Maleah]
Valentina       f           Italian                [Tina]
Kimberly        f           English      [Kim, Kimberlee]
Kaitlyn         f  English (Modern)    [Caetlin, Caitlin]
Maria          fm           Italian          [Jet, Jette]
Michelle        f            French       [Chelle, Micha]
Juliana         f             Dutch    [Iuliana, Juliane]
Mackenzie      fm           English  [Makenzie, Mckenzie]
Madelyn         f           English     [Madalyn, Maddie]
Miriam          f            Hebrew              [Mirjam]
Scarlett        f           English             [Scarlet]
Genesis         f  English (Modern)                    []
Julianna        f         Hungarian   [Juliana, Julianne]
Stella          f           English            [Styliani]
London         fm  English (Modern)              [Londyn]
Natalia         f            Polish           [Nat, Nata]
Sydney         fm           English       [Cydney, Sydne]
Serenity        f  English (Modern)                    []
Faith           f           English         [Fae, Faithe]
Gabrielle       f            French      [Brielle, Gabby]
Jessica         f           English       [Gessica, Jess]
Morgan         mf             Welsh    [Morgaine, Morgen]
Naomi           f           English                    []
Paige           f           English                    []
Rebecca         f           English        [Becca, Becci]

[100 rows x 3 columns]

In [ ]:
# SQL DataBase connection:
connection_string = "root:Ag8998999!@localhost/Dog_vs_Human_Names_db"
engine = create_engine(f'mysql://{connection_string}')

In [ ]:
# Connection Test:
engine.table_names()

In [ ]:
# Export dog name data to SQL:
dog_names_df_clean.to_sql(name='dog_names', con=engine, if_exists='append', index=True)

In [ ]:
# Export human name data to SQL:
state_names_2000_NY_df.to_sql(name='state_names', con=engine, if_exists='append', index=True)

In [ ]:
# Export name origin data to SQL: